name: Cross-Platform Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20, 22]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: Type check
      run: bun run typecheck

    - name: Build project
      run: bun run build

    - name: Test CLI help command
      run: node dist/index.js --help

    - name: Test CLI today command (JSON output)
      run: node dist/index.js today --json

    - name: Test CLI session command (JSON output) 
      run: node dist/index.js session --json

    - name: Test show-models option
      run: node dist/index.js today --show-models false --json

    - name: Verify package contents
      run: npm pack --dry-run

    - name: Test global installation (Unix-like)
      if: matrix.os != 'windows-latest'
      run: |
        npm pack
        npm install -g ocusage-*.tgz
        ocusage --help
        npm uninstall -g ocusage

    - name: Test global installation (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        npm pack
        $file = Get-ChildItem -Name "ocusage-*.tgz"
        npm install -g $file
        ocusage --help
        npm uninstall -g ocusage